### ISSUE TITLE
Evaluating only bounding boxes

### ISSUE THREAD

**Issue by MathiasHaudgaard** [BigRedT/no_frills_hoi_det#1]
Thanks for this awesome project 👍 

I was wondering if it's possible to evaluate the predicted bouding boxes on the hico-det dataset without looking at the interaction?
I would like to see how different detectors perform on the dataset :shipit: 

Cheers

**Comment by BigRedT** [comment]
I think you can do an AP evaluation for human detections because they should be exhaustively annotated in HICO-Det. Objects other than human, however, may not be exhaustively annotated since only instances that are interacting with a human would be annotated. Hence precision cannot be computed for non-human objects. 

You could still perform a recall based evaluation to see what fraction of ground truth detections are recalled by an object detector. See the table in [https://github.com/BigRedT/no_frills_hoi_det#step-3-select-candidate-boxes-for-each-object-category-from-all-predictions](https://github.com/BigRedT/no_frills_hoi_det#step-3-select-candidate-boxes-for-each-object-category-from-all-predictions) for an example of such an evaluation.
