### ISSUE TITLE
Questions about the HOI candidates

### ISSUE THREAD

**Issue by MathiasHaudgaard** [BigRedT/no_frills_hoi_det#4]
I've been playing around with the HOI candidate files which led to some questions.
Why are you including hoi candidates with low object detection scores?
Why are you including hoi candidates where the human and object are the same bounding box? (this only concerns the case where object=human)

**Comment by BigRedT** [comment]
Q. Why are you including hoi candidates with low object detection scores?
A. We want to have high recall of objects. If we miss an object candidate, the HOI classifier is not going to be able to fix it and so I figured it is better to err on the side of caution and have a low detection threshold. Even that low detection threshold is actually surprisingly good at getting rid of a lot of false positives! Finally, since the final HOI score is a product of detection and interaction terms, candidates who have lower detection scores would get a low HOI score as well. 

Q. Why are you including hoi candidates where the human and object are the same bounding box? (this only concerns the case where object=human)
A. You can get rid of those if you like. I just thought it was cleaner to treat all object categories the same way and let the model learn the right behavior.
